### ISSUE TITLE
Can't sign-in to Google

### ISSUE THREAD

**Issue by RuchirChawdhry** [agata/dl.biscuit#28]
Can't sign-in to any Google service with this. This is what it displays:
![Screen Shot 2020-08-25 at 08 48 39](https://user-images.githubusercontent.com/4688811/91119026-e42c5f80-e6af-11ea-9c79-ab6022df4ce7.png)

Using macOS Mojave

**Comment by agata** [comment]
@RuchirChawdhry 

Please try setting up the following User-Agent on Preferences.

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36 Edg/79.0.309.65

**Comment by agata** [comment]
or Install latest version.

https://github.com/agata/dl.biscuit/releases/tag/v1.2.10

**Comment by mexson** [comment]
Hi, I am on v. 1.2.10 and set up user agent to the one you mentioned but it's still not working
I am on Windows 10

Edit: This issue also appeared on other all-in-one messaging apps such as Rambox and Ferdi (not sure about the latter) so I suspect that Google made some changes that are interfering with electron

**Comment by RuchirChawdhry** [comment]
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36 Edg/79.0.309.65

@agata 
This did actually work for me, for whatever reason. Weird that all the macOS user-agents I'd tried didn't work for me.

 I thought it'd share the cookies across a group - but I had to login 3 times (3 different sessions) for Google Keep, GMail & GDrive.

**Comment by agata** [comment]
Released 1.2.11 with fixed this issue. Please check it.
https://github.com/agata/dl.biscuit/releases/tag/v1.2.11.

**Comment by reud** [comment]
Hello.

In MacOS 11.0, I also found that logging in via Google was not possible for me.

Oddly enough, I was able to log in to Gmail, Slack(G Suite), and Gmail with my Google account, but not with Notion.

I'm sorry for the Japanese, but here is a screenshot.

version 1.2.11

![image](https://user-images.githubusercontent.com/31179220/92435647-d1e91000-f1dd-11ea-8466-88e791a692f8.png)

![image](https://user-images.githubusercontent.com/31179220/92435743-0d83da00-f1de-11ea-90d8-28d523f90cf9.png)

**Comment by agata** [comment]
@reud I don't run Biscuit on MacOS 11.0 yet. Do you have a custom user agent set up? If you don't have, try setting up the following user agent.

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 Edg/83.0.478.61

or if you set up custom user agent, please clear it and relaunch Biscuit.

ps. I can read Japanese ;-)

**Comment by reud** [comment]
@agata 
返信ありがとうございます。日本語で話させて頂きます 🙇 

UAの変更を行いましたが、状況は変わらずで、Loginするメールアドレスを変更した所、ログインに成功しました。
Googleアカウント依存なのですかね・・・お騒がせしました。対応ありがとうございました！

**Comment by agata** [comment]
> UAの変更を行いましたが、状況は変わらずで、Loginするメールアドレスを変更した所、ログインに成功しました。
> Googleアカウント依存なのですかね・・・お騒がせしました。対応ありがとうございました！

@reud なるほど、貴重な情報です。ログインできたアカウントとログインできなかったアカウントでなにか特徴はありましたか？(例: G Suiteで管理されているアカウントなど)

**Comment by reud** [comment]
@agata いいえ、G Suite管理ではありませんでした。特徴は思いかびませんね・・・ 
2段階認証を設定している方がログインできず、ログイン出来た方のGoogleアカウントは2段階認証を設定していませんでした。ご参考になれば。
