### ISSUE TITLE
Can't login to gmail

### ISSUE THREAD

**Issue by pempek** [agata/dl.biscuit#38]
### The issue 
I was trying to login to my gmail account, but encountered this error:
![image](https://user-images.githubusercontent.com/36126710/129145880-994ca653-de30-4f0c-9f12-1464f8491848.png)

Expected behavior:
Able to login to my gmail account.

Biscuit version1.2.20 on Windows 10
![image](https://user-images.githubusercontent.com/36126710/129146035-fd45c43b-8e30-4642-8943-9c24375720bf.png)

**Comment by jzyang617** [comment]
I'm having the same issue but only if I try to start a new app. I'm afraid to log out of any of my apps that I have the password saved out of fear that I won't be able to get back in. Weirdly, I can log into other gmail accounts but for most of my other personal accounts that I've made years ago, this error message keeps coming up. This is a serious problem as I need to use my gmail to login to several other apps, which now I'm not able to do at all. If I am logged out of any of those accounts, I'm screwed. Please provide a fix for this!

**Comment by agata** [comment]
@jzyang617 @pempek Fixed it. Please use latest version. Thanks!

**Comment by jzyang617** [comment]
Amazing! Thank you, it works now.

**Comment by pempek** [comment]
> @jzyang617 @pempek Fixed it. Please use latest version. Thanks!

Thank you very much for the update!

(Now I just need to wait for the update on AUR haha)
