### ISSUE TITLE
WhatsApp doesn't work after update to 1.2.21

### ISSUE THREAD

**Issue by dplitzko** [agata/dl.biscuit#39]
After updating to 1.2.21, WhatsApp no longer works.
It shows a message that says:

> WhatsApp works with Google Chrome 60+.
> To use WhatsApp, update Chrome or use Mozilla Firefox, Safari, Microsoft Edge or Opera.

![image](https://user-images.githubusercontent.com/11302733/130065248-2871fa3b-71ef-41ae-836b-95dcf2a39ab8.png)

I restarted biscuit and deleted and recreated the WahtsApp tab, but nothing changed.

**Comment by agata** [comment]
@dplitzko We've released v1.2.22 and fixed it. Thanks!
