### ISSUE TITLE
Problems with non-english keyboard

### ISSUE THREAD

**Issue by sergio-faraldo** [agata/dl.biscuit#4]
I basically cannot type an "@" sign using my spanish keyboard. It is like the keypress doesn't register.
In the spanish keyboard, @ is typed with AltGr+2, btw.

**Comment by sergio-faraldo** [comment]
Just to clarify, I'm on Windows 10 and I am running the latest version of biscuit.
AltGr+1(|), AltGr+3(#), AltGr+4(~) and AltGr+6(¬) don't work either, but all other AltGr+key combinations work fine.

**Comment by jerome-breton** [comment]
Up on this one. I have the same problem with Win10 and French keyboard. "@ " sign is made with AltGr+0.

It seems that AltGr+numbers are bound to switching left tabs but prevent inputing special chars.

IMHO, switching tabs should be bound to Ctrl+number like traditionnal browsers do.

**Comment by sergio-faraldo** [comment]
It's been fixed a while ago, just closing this since the devs didn't
